version: "3.9"

# The services of nestjs application build with dockerfile
services:
  nest_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:debug
    container_name: nestjs-starter-app
    depends_on:
      - postgresql-master
      - postgresql-slave
    volumes:
      - .:/usr/src/app
      # copy file from container to host on path ./node_modules/.prisma/client
      - ./node_modules/.prisma/client:/usr/src/app/node_modules/.prisma/client
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "${PORT}:3000"
      # debug port
      - "9229:9229"
    networks:
      - app-network

  web_server:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    depends_on:
      - nest_app
      - postgresql-master
      - postgresql-slave
    ports:
      - "9000:80"
    networks:
      - app-network

  postgresql-master:
    image: docker.io/bitnami/postgresql:14
    platform: linux/amd64
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    env_file:
      - .env
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      # - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

  postgresql-slave:
    image: docker.io/bitnami/postgresql:14
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - '${POSTGRES_SLAVE_PORT}:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      # - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:6.18
    depends_on:
      - postgresql-master
      - postgresql-slave
    ports:
      - '5050:80'
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  postgresql_master_data:
    driver: local
  pgadmin_data:

# gateway-network
networks:
  app-network:
